### ISSUE TITLE
Adjust user model to include properties for Property Managers

### ISSUE THREAD

**Issue by dbridenbeck** [codeforpdx/dwellinglybackend#41]
**Expected Behavior**
When GET /user/:id is called for a Property Manager, the properties they manage and the tenants that belong to those properties should be returned

pseudo-code from Hugh on how to accomplish this:
```
if role == "PROPERTY MANAGER":
 return user.json w/ properties
```

**Comment by DaveTrost** [comment]
Moved this issue to the front-end repo. All issues are being tracked there (even the back-end issues)
